"use client";

import "./globals.css";
import Navbar from "../components/header/Navbar";
import Footer from "../components/footer/Footer";
import { Poppins } from "next/font/google";
import { useEffect } from "react";
import { useParams } from "next/navigation";
import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = window.location.pathname;

  return (
    <html lang="en">
      <body>
        {path !== "/login" && <Navbar />}
        <main className={`main-container ${poppins.className}`}>
          {children}
        </main>
        {path !== "/login" && <Footer />}
      </body>
    </html>
  );
}
