import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/header/Navbar";
import Footer from "../components/footer/Footer";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight:'400'});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        <div className="main-container">
          <main className={poppins.className}>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
